# Generated by Django 4.1.7 on 2023-03-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.CharField(blank=True, max_length=80, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('identity', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_job', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_line', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('github', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp', models.IntegerField(blank=True, null=True)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('strength', models.JSONField(blank=True, null=True)),
                ('soft_skills', models.JSONField(blank=True, null=True)),
                ('hard_skills', models.JSONField(blank=True, null=True)),
                ('goals', models.JSONField(blank=True, null=True)),
                ('technologies', models.JSONField(blank=True, null=True)),
                ('libraries', models.JSONField(blank=True, null=True)),
                ('frameworks', models.JSONField(blank=True, null=True)),
                ('microframeworks', models.JSONField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='files')),
                ('illustrations', models.ImageField(blank=True, null=True, upload_to='files')),
                ('graphics_design', models.ImageField(blank=True, null=True, upload_to='files')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('certifications', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
