# Generated by Django 4.1.7 on 2023-03-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='achual_job',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='artistic_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='frameworks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='goals',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='graphics_design',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='hard_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='identity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='illustrations',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='libraries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='microfreameorks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='short_description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='soft_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='strength',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='tag_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='technologies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='whatsapp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
