# Generated by Django 4.1.7 on 2023-03-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer_profile', '0002_developerprofile_achual_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developerprofile',
            old_name='microfreameorks',
            new_name='microframeorks',
        ),
    ]
