# Generated by Django 4.1.7 on 2023-03-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer_profile', '0003_rename_microfreameorks_developerprofile_microframeorks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developerprofile',
            old_name='microframeorks',
            new_name='microframeworks',
        ),
    ]
