# Generated by Django 4.1.7 on 2023-03-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer_profile', '0004_rename_microframeorks_developerprofile_microframeworks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developerprofile',
            old_name='achual_job',
            new_name='actual_job',
        ),
    ]
